---
title: "CS2002-W08-Practical-Report"
author: "120011222"
date: "9 April 2018"
output:
  html_document:
    df_print: paged
---

# Practcial4 - Stabilising circuits

------

### Overview

In this practical it was our task to undertake various and implement various tasks related to knowledge of digital circuits with feedback, as well as logic gates and truth tables.

### Specification

A digital circuit with feedback is called stable if the value of each wire (which can be 0 or 1) remains unchanged over time. We say a circuit stabilises if eventually it becomes stable. Some circuits stabilise for certain input values but not for others. In this practical we explored the simulation of digital circuits to determine for which inputs they stabilise. Our task was to write a program, in the C programming language to read and parse a block of CDL (Circuit description language - see appendix for details) text, and translate this into a data structure representing the digital circuit that the CDL text describes, and then simulate this circuit multiple times with different initial input values to compute and output a truth table (see appendix for example of truth table)


### Extensions

For this practical, I implemented two extensions, both of which were recommended and approved.

1. An option for both asynchronous and synchronous simulation.

The recommended and required way for the basic specification is *synchronous* sumulation. This is where the state in each wire at time (t) is calculated by looking at the state of its input wires at time (t - 1). So the state of each wire all change simulatneously, in synchronisation with each other. 

When considering *asynchronous* simulation, there is no ordering, and no time sequence. In other words, the state of each wire at each time is calculated by looking at the

state of each wire also at the current time. So time never 'advances' as such, rather we Iterate through the circuit multiple time repeatedly calculating the state of each wire as function of the states in all other wires in the circuit. 

This is best illustrated with an example: 

My program includes the function:

```{C}
void printTimeseries(bool synchronous);
```

where the argument `synchronous` indicates either synchronous (if true) or asynchronous (if false) simulation.

Here is an example of a timeseries, calculated with the circuit described the CDL example in the appendix, this is calculated with synchronous simulation. 

***


2. An option to gradually change the values of the input wires whilst the circuit is still in simulation, to see whether the circuit will stabilise in this way, even if it doesnt stabilise when the same input values are supplied as initial values (i.e when all other wires in the circuit are reset to 0) 

Again, this concept is best illusrated with an example. 

The program includes the function:

```{C}
void printTruthtable(bool resets);
```

where the argument `resets` indicates whether the truth table should be constructed where the value of the input wires gradually changes whilst the circuit is still in simulation (if false) or whether the value of all other wires should be reset to 0 when the inputs are changed (if true.) The basic specification requires this argument to be true by default. The image below shows an example of a truth table, constructed with the circuit described the CDL example in the appendix, and computed with this argiment set to true (the standard setting).




  
*****

### Design

When carrying out the specification, eventually, I ended with two different implementations, and two executables. The two executables are named `readmymind` and `readmymind_2` Both implementations however, feature the following struct definition to represent a Playing card.

```
typedef struct {
	 	char* suit;
		char face;
	} Card; 
```

The `suit` field of the struct is of type `char*` which is effectively a String, so it will be able to reference a unicode character which gives a text character symbol for the four suits in a deck of playing cards, rather than just a single character for 'H','S','C','D'.  Supporting this feature can be con considered an extension for this practical. 

The main difference between the two implementations was centered around this distinction between arrays and pointers. Once I had defined a `Card` It was then possible to define a `Deck` (of 52 cards), either as a Card[52], or as a Card*, or by

```
typedef Deck[52] Card;

```
Similarly a `Pile` (of 7 cards), a a `Pileset` (of 3 piles) may also have three differing defintions, thus a `Pileset` could either be declared as a
```
Card** pile;

-or-
typedef Pile[7] Card;
typdef Pileset[3] Pile;
```


I initially found this distinction confusing, but have discussed what I learnt about the functionality of arrays and pointers below.

Another major design decision I made was to avoid the use of magic numbers, and so for all constants involved in the porogram, they were fined as preproccesor directives such as:

```{C}
#define           N_DECK 52
#define           N_SUITS 4
#define           N_FACES 13
#define           N_PILE 7
#define           N_SET 3
#define           N_SORT 4
```

And then everywhere else in the program I needed to use these numbers, I could refer to them via `N_SET` rather than `3` The advantage of this was that it would easily allow me to change every occurence of this number in the program simply by changing one line in the header file. Another of the possible extensions was
to experiment and find out if the trick worked for different values of the number of piles in a set, ot the number of cards in a pile, and this implementation allowed me easily to do that. I found that wih the current settings for N_PILE and N_SET, N_SORT could be incremented, and the trick would still function as usual, although could not find any alternate further values apart from this. With regards to the length of the columns, I found that any odd length of column that is divisible by 3 will also work. However, if the length of column is more than 11 than the trick requires 4 iterations of the sort(...) and gather(...) process to complete, whereas any less than 11, 3 itetaration will be sufficient.

A final point on my design decisions involves the use of tge `memcpy(src, dest, size)` function that copies memory the contents of one memory address to another memory address. The memcpy() function is defined in the library `<string.h>` and I used this in place of regular assignment involving pointers. I have justified my decision to do this below:
```{C}
char *ptr;
char *string = malloc(sizeof(char) * 10);
```
****
```{C}

ptr = string;

vs.

memcpy(ptr, string, sizeof(string));

```

The straight assignment will change the variable ptr to point to the same location that string points to, so they both are the same.  However memcpy() will copy sizeof(string) bytes from the location string points to to the location ptr points to, creating a new replica and pointing to that. If, however, ptr has not been initialized to point to a block of memory large enough to contain that many bytes, or if it has not been initialized at all, then the behavior is undefined. After the memcpy(), then each pointer points to a separate copy of the same data. Freeing one of them frees only that copy so it is still ok to dereference the other one.

Therefore when using malloc() and free() when declaring pointers, using memcpy() will ensure the value pointed to by each pointer variable remains distinct from eachother, and it safe to call free()

Another point is that since memcpy is therefore equivalent to the x86 assembkly command `mov` using memcpy in preference of assignemnt allows further room for compiler optimisation.


__On the distinction between arrays and pointers:__

Pointers and arrays are not equivalent, and a pointer expression is not generally equivalent to an array expression, however in some respects, they are similar. For example, Pointer arithmetic and array indexing are equivalent. Indexing works on both arrays and pointers. Similarly, pointer arithmetic works on both arrays and pointers, although the pointer implementation will always generally be faster. In other aspects, pointers and arrays are different. However when arrays passed into functions, they are always converted into pointers. The argument declaration char arr[3] is just syntactic sugar for char* arr. For an array, the comiler places the array at a fixed memory location.
However, a pointer is an object that holds a memory address. Pointers are used to refer to memory where the data resides.
Pointers are used for flexibility: you can refer to another object at run-time by changing the memory address stored inside the pointer variable.

However, when an array name is passed to a function, what is passed is the location of the initial element. Within the called function, this argument is a local variable and so an array name parameter is a pointer, that is, a variable containing an address. 


*****
### Testing

To test the the program, I used the llvm debugger to examine the assembly instructions and ensure each phase of the program was running as usual. I then also used valgrind to check there were no memory leaks from dynamically allocated blocks, see screenshot below.


****


### Running the program

To compile and link the source files needed for both programs, please use the Makefile provided, along with the `all` target:

```
$ make all

```

This should produce the two executables, readmymind and readmymind_2.

*****

### Conclusion

Overall, I believe the practical was a success. I successfully completed all requirements, as well as some extensions. I believe this report documents and explains my findings well. The main diffuculties I encountered when dealing with arrays and pointers I overcame well, and have discussed in the _Design_ section.

