.TH "CircuitNode" 3 "Tue Apr 10 2018" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CircuitNode
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <circuits\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBstate\fP"
.br
.ti -1c
.RI "char * \fBid\fP"
.br
.ti -1c
.RI "char * \fBfunc\fP"
.br
.ti -1c
.RI "struct \fBCircuitNode\fP * \fBout\fP"
.br
.ti -1c
.RI "struct \fBCircuitNode\fP * \fBinp_1\fP"
.br
.ti -1c
.RI "struct \fBCircuitNode\fP * \fBinp_2\fP"
.br
.ti -1c
.RI "unsigned int \fBstates\fP [\fBmax_circuit_time\fP]"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "char* CircuitNode::func"

.SS "char* CircuitNode::id"

.SS "struct \fBCircuitNode\fP* CircuitNode::inp_1"

.SS "struct \fBCircuitNode\fP* CircuitNode::inp_2"

.SS "struct \fBCircuitNode\fP* CircuitNode::out"

.SS "int CircuitNode::state"

.SS "unsigned int CircuitNode::states[\fBmax_circuit_time\fP]"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
